# https://github.com/bitnami/containers/blob/main/bitnami/spark/docker-compose.yml

services:
  spark:
    build:
      context: .
      dockerfile: Dockerfile
    image: spark:latest
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
      - SPARK_SQL_EXTENSIONS=io.delta.sql.DeltaSparkSessionExtension
      - SPARK_SQL_CATALOG=spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 5s
      timeout: 3s
      retries: 3
    ports:
      - 7077:7077
      - 8080:8080
    volumes:
      - ../src/work:/opt/bitnami/spark/work
  spark-worker:
    image: spark:latest
    depends_on:
      - spark
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    volumes:
      - ../configs/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf